version: "3.8"
services:
  springboot:
    image: buyornot/docker-springboot
    container_name: springboot
    networks:
      - buyornot_net
    restart: "always"
  nginx:
    image: buyornot/docker-nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - buyornot_net
    restart: "always"
networks:
  buyornot_net:
    driver: bridge