version: "3.8"
services:
  springboot:
    image: buyornot/docker-springboot
    container_name: springboot
    restart: "always"

  nginx:
    image: buyornot/docker-nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - springboot
    restart: "always"