version: "3.8"

  services:
    springboot:
      image: "buyornot/docker-springboot"
      restart: "always"

    nginx:
      image: "buyornot/docker-nginx"
      ports:
        - "80:80"
      restart: "always"

