version: "3.8"

  springboot:
    image: "buyornot/docker-springboot"
    restart: "always"

  services:
    nginx:
      image: "buyornot/docker-nginx"
      ports:
        - "80:80"
      restart: "always"

