version: "3.8"
services:
  springboot:
    image: buyornot/docker-springboot
    container_name: springboot
    ports:
      - "8080:8080"
    networks:
      - backbone
    restart: "always"

  nginx:
    image: buyornot/docker-nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - default
      - buyornot_net
    depends_on:
      - default
      - buyornot_net
    restart: "always"

networks:
  buyornot_net:
    driver: bridge