name: CI

on:
  pull_request:
    branches: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.RDS_HOST}}
          spring.datasource.username: ${{ secrets.RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
          cloud.aws.credentials.accessKey: ${{ secrets.S3_ACCESS }}
          cloud.aws.credentials.secretKey: ${{ secrets.S3_SECRET }}
          cloud.aws.s3.bucket: ${{ secrets.S3_BUCKET }}
          spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
          spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
          spring.security.oauth2.client.registratin.naver.clinet-id: ${{ secrets.NAVER_CLIENT_ID }}
          spring.security.oauth2.client.registratin.naver.clinet-secret: ${{ secrets.NAVER_CLIENT_SECRET }}
          jwt.key: ${{ secrets.JWT_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

