name: CI

on:
  pull_request:
    branches: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create yml files
        run: |
          mkdir ./src/main/resources
          cd ./src/main/resources
          touch application.yml
          touch application-aws.yml
          touch application-oauth.yml
          echo "${{ secrets.APPLICATION_YML }}" >> application.yml
          echo "${{ secrets.APPLICATION_AWS_YML }}" >> application-aws.yml
          echo "${{ secrets.APPLICATION_OAUTH_YML }}" >> application-oauth.yml
          
          mkdir firebase
          touch ./firebase/firebase_service_key.json
          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
          sed -i 's/#/"/g' ./firebase/firebase_service_key.json
        shell: bash

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

